name: doctrina-dev
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - nodejs=18
  - pip:
      - aws-cdk-lib
      - awscli
      - boto3
      - clize
      - git-remote-codecommit
      - ipython
      - python-dotenv
