channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pip
  - python=3.11
  - pip:
    - accelerate
    - bitsandbytes
    - boto3
    - clize
    - cython
    - datasets
    - diffusers
    - ipython
    - ipykernel
    - ipywidgets
    - matplotlib
    - mlflow
    - plotly
    - torch
    - torchaudio
    - torchvision
    - python-dotenv
    - requests
    - sentencepiece
    - scikit-learn
    - seaborn
    - tokenizers
    - transformers
