channels:
  - conda-forge
  - pytorch
dependencies:
  - bitsandbytes
  - cudatoolkit=11.2.2
  - ipython
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - pytorch<2
  - torchaudio
  - torchvision
  - pip:
    - accelerate
    - boto3
    - clize
    - cython<3.0.0
    - datasets
    - diffusers
    - ipywidgets
    - mlflow
    - plotly
    - python-dotenv
    - requests
    - s3fs
    - seaborn
    - tokenizers
    - transformers
