dependencies:
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyspark
  - pytables
  - python
  - pip:
    - boto3
    - clize
    - ipykernel
    - ipython
    - matplotlib
    - mlflow
    - python-dotenv
    - requests
    - s3fs
    - scikit-learn
    - seaborn
