dependencies:
  - nodejs>=13
  - pip
  - python
  - pip:
    - ipython
    - ipywidgets
    - jupyter_console
    - jupyterlab
    - jupyterlab-git
    - jupyterlab-vim
    - jupyterlab_widgets
    - plotly
