dependencies:
  - ffmpeg
  - matplotlib
  - numpy
  - pandas
  - pip
  - protobuf
  - pyarrow
  - python
  - tensorflow=2.8.1=cuda*
  - pip:
    - awscli
    - boto3
    - cachetools
    - ftfy
    - fiftyone
    - ipykernel
    - ipython
    - ipywidgets
    - kaggle
    - keras-tuner
    - line_profiler
    - regex
    - requests
    - s3fs
    - scikit-learn
    - seaborn
    - statsmodels
    - tensorflow-hub
    - tensorflow_addons
    - transformers
    - tqdm
