dependencies:
  - beautifulsoup4
  - bokeh
  - ipython
  - ipykernel
#  - ipywidgets>=7.5
#  - joblib>=0.13
#  - jsonschema>=3.0
#  - line_profiler>=2.1
  - matplotlib
  - numpy
#  - opencv>=4
  - pandas
  - pillow
  - pip
  - pyarrow
#  - pyqt>=5.12
  - python>=3.9
  - requests
#  - s3fs
  - scikit-learn>=0.21
  - scipy
  - seaborn
  - pip:
#    - boto3>=1.9
    - clize
    - opencv-python
#    - kaggle>=1.5
#    - pydevd-pycharm
